services:
  aide:
    build:
      context: .
    image: outstand/aide:dev
    working_dir: ${WORKSPACE_DIR}
    volumes:
      - bundler-data:/usr/local/bundle
      - .:${WORKSPACE_DIR}
    ports:
      - "3000"
    environment:
      FIXUID:
      FIXGID:
      WORKSPACE_DIR:

  release_gem:
    image: outstand/aide:dev
    command: rake release
    working_dir: ${WORKSPACE_DIR}
    environment:
      FIXUID:
      FIXGID:
      WORKSPACE_DIR:
    volumes:
      - bundler-data:/usr/local/bundle
      - .:${WORKSPACE_DIR}
      - ~/.dotfiles/config/git/gitconfig:/home/deploy/.gitconfig
      - ~/.dotfiles/config/git/gitconfig.user:/home/deploy/.gitconfig.user
      - ~/.config/gh/hosts.yml:/home/deploy/.config/gh/hosts.yml
      - ~/.local/share/gem/credentials:/home/deploy/.local/share/gem/credentials
      - ~/.local/share/gem/credentials:/home/deploy/.gem/credentials

volumes:
  bundler-data:
